# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e246c8696a6700a08f11425ba1712bf92663c654068a21ec3a2933f533e5eda625f2ec2a61e31bdb79236cd9782079e0bbcf06a7bcd460195a048343d6e7f68c

test:
  secret_key_base: 568d1e5862f02151321fce805f31b8e015b2eac161cb6952e0b04c75572f695905e24ecfe0416b1bb8b6e35af3c53abb36ee18359a1bf89a52e7bb84572c0135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
